{% set name = "django-anymail" %}
{% set version = "10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_anymail-{{ version }}.tar.gz
  sha256: 35d8ec20b06000af3c1638492e32f416fd1a584f0a572cded03f1bc570169ed0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - django >=2.0
    - requests >=2.4.3
    - urllib3 >=1.25.0

about:
  home: https://github.com/anymail/django-anymail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Django email backends and webhooks for Mailgun, Mailjet, Postmark, SendGrid, SparkPost and more '
  description: |
    Anymail integrates several transactional email service providers (ESPs) into Django, with a consistent API that lets you use ESP-added features without locking your code to a particular ESP.
    It currently fully supports Mailgun, Mailjet, Postmark, SendGrid, and SparkPost, and has limited support for Mandrill.
  doc_url: https://anymail.readthedocs.io/en/stable/
  dev_url: https://github.com/anymail/django-anymail

extra:
  recipe-maintainers:
    - cshaley
    - elanqo
    - zaigner
    - millsks
    - rxm7706
