{% set name = "django-anymail" %}
{% set version = "8.0" %}
{% set sha256 = "9a0a7d3f0722d0b4509548051b0d7578384e7d2d65112fc01c1ce66e5e16ae0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8
    - requests >=2.4.3
    - six

about:
  home: https://github.com/anymail/django-anymail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Django email backends and webhooks for Mailgun, Mailjet, Postmark, SendGrid, SparkPost and more '
  description: |
    Anymail integrates several transactional email service providers (ESPs) into Django, with a consistent API that lets you use ESP-added features without locking your code to a particular ESP.
    It currently fully supports Mailgun, Mailjet, Postmark, SendGrid, and SparkPost, and has limited support for Mandrill.
  doc_url: https://anymail.readthedocs.io/en/stable/
  dev_url: https://github.com/anymail/django-anymail

extra:
  recipe-maintainers:
    - cshaley
    - elanqo
    - zaigner
    - millsks
    - rxm7706
